Fix narrowing compiler issues
When compiling cmds.So, the compiler can raise the following error:
`../lib/bdlib/src/base64.h:56:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]`

A workaround has been committed upstream, but as cmds code includes
the header, there is a need to apply the same workaround here too.

References:
  - https://github.com/bdrewery/bdlib/issues/4
  - https://clang.llvm.org/docs/DiagnosticsReference.html#wnarrowing
  - https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html